### ISSUE TITLE
Syntax highlighting bug on argument/return type annotations

### ISSUE THREAD

**Issue by Skuzzzy** [atom/language-python#112]
There seems to be an issue with type hinting. PEP483 https://www.python.org/dev/peps/pep-0483/

Example of issue here
https://github.com/Skuzzzy/chrome-bookmark/blob/master/chrome-bookmark.py#L8

github/linguist repository uses atom/language-python for python syntax highlighting if I understand correctly

Edit: I downloaded Atom and tested the file there, it works fine. I was misled by a issue on github/linguist that I should post this issue here.

**Comment by Potato42** [comment]
Are you really not having the problem in atom?  I was going to post this issue myself because type annotations didn't work.
What it looks like for me:
Function with type annotations (ruins everything)
![typeanno-atom](https://cloud.githubusercontent.com/assets/8140726/10920821/269a1580-8227-11e5-8d0e-86014d152b16.png)
No type annotations
![no-typeanno-atom](https://cloud.githubusercontent.com/assets/8140726/10920822/26b5e9cc-8227-11e5-91e6-17668acbdf83.png)

Argument type annotations don't ruin things to the extent that return value annotations do, but they still look a bit weird.

**Comment by forana** [comment]
:+1: this is currently annoying the hell out of me as well. seeing the same thing as Mr. Potato here. version 1.1.0, everything up to date.

**Comment by Potato42** [comment]
However, this looks like it's already open at #68

**Comment by 50Wliu** [comment]
Closing in favor of #68.
