### ISSUE TITLE
tab problem

### ISSUE THREAD

**Issue by char256** [atom/language-python#169]
when i try to set tab as two spaces, i can't change it. the only way i can fix this is to disable the language-python package. once i enable the package, no matter what i do, tab is 4 spaces.

**Comment by thomasjo** [comment]
According to PEP 8, Python code should be [indented with 4 spaces](https://www.python.org/dev/peps/pep-0008/#indentation). Because of this, the language-python package uses 4 spaces by default.

If you want to change this for Python code, you can change this via the language-python settings page. Simply set the *Tab Length* setting for language-python to 2 spaces.

**Comment by JellyWX** [comment]
This is not fixed. You cannot change the tab length

**Comment by zactionman** [comment]
If I set tab length to 2 in language-python settings hitting tab inserts 4 spaces. Other lengths seem to work as expected.

Atom Version 1.14.4
language-python version 0.45.1
