### ISSUE TITLE
Python Indentation Issues

### ISSUE THREAD

**Issue by JellyWX** [atom/language-python#183]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Python automatically indents 4 spaces when set to indent to 2 in the `language-python` settings and the `editor` settings. 

### Steps to Reproduce

1. Clear the python section in the atom config
2. Set indentation to 2 in the `editor` settings and the `language-python` settings (should say `Unscoped Value: 2`)
3. Open up a python file and hit the tab key

**Expected behavior:** Tabs to 2 spaces

**Actual behavior:** Tabs to 4 spaces

**Reproduces how often:** On every install of Atom; for me probably about 5 different machines 100% of the time.

### Versions

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.6
git 1.9.1

OS: Ubuntu 16.04, Ubuntu 14.04, Windows 8.1

### Additional Information

It is possible to manually fix by entering the config file and adding the line `tabLength: "2"` under python, since just `tabLength: 2` will automatically be deleted by the editor.

**Comment by 50Wliu** [comment]
This language package follows the PEP8 conventions, which is to use 4 spaces for the tab length.

**Comment by JellyWX** [comment]
but that doesnt make the issue resolved: the setting dont work for it. if theyre not supposed to work then dont put them in

**Comment by JellyWX** [comment]
Please reopen this issue. It is not resolved at all and is still a bug

**Comment by 50Wliu** [comment]
I cannot reproduce this issue on Windows 10, Atom 1.15.0-dev-ae6a7a0:
![python-two-space-indent](https://cloud.githubusercontent.com/assets/2766036/22800748/5e0fe412-eed8-11e6-8acc-17ce7e6d7b69.gif)

**Comment by JellyWX** [comment]
![screenshot from 2017-02-09 20 36 58](https://cloud.githubusercontent.com/assets/5578434/22802140/9c938818-ef07-11e6-976f-39d1722c72cd.png)

Thank you for reopening this case. Whilst I can't make a fancy gif like that I can try and provide a useful enough screenshot? Taken on Ubuntu 14.04

**Comment by JellyWX** [comment]
+ i freshly installed atom and I'm on 1.13.1. i dont know why it's not 1.15, since i downloaded it yesterday off the atom.io website (the .deb package)

**Comment by 50Wliu** [comment]
Yeah, I'm running the latest development version, which _was_ 1.15 but changed to 1.16 yesterday (the latest stable version, 1.14, was released yesterday - probably a bit after you downloaded it).

Anyway, I think I see the problem now.  I missed the part where you said that you have your global tab length preference set to 2, so language-python is overriding it and you can't manually set it back.  Tricky...

However, this issue is out of the scope of language-python and is a larger issue present in the [settings-view](https://github.com/atom/settings-view) package.  Can you please reopen this issue there?

**Comment by sudarshan85** [comment]
I think this should be reponed. I'm using Atom 1.14.1 on Ubuntu 16.04 and I am having this problem. That the problem is only with the value 2. If I put 3 on tab length it works. But for some reason, if I put 2 it doesn't jump 2 spaces it jumps 4 spaces. This is a really annoying bug and I don't think it has anything to with settings-view.

**Comment by 50Wliu** [comment]
It's a bug with settings-view because settings-view isn't allowing you to override a scoped setting if your unscoped setting is different.  In this case, yes, unscoped value means the default value.

**Comment by naturalethic** [comment]
@JellyWX Hey Jude, can you open a new ticket on https://github.com/atom/settings-view with the same description and link it in here.  I'd do it but I don't have access to the raw source of your original description.  I also feel the ticket should be tracked in here @50Wliu.  When they close it there, close it here.

**Comment by fserb** [comment]
For anyone ending up here and seeing non-helpful messages. Yes, there's a problem with how language-python default tab length interacts with atom/settings-view. If you are going mad over this, here's the temporary solution:

You can directly edit the configuration file (`config.cson`, or `Atom > Config...`). Add the following toplevel:
```
".python.source":
  editor:
    tabLength: 2
```

This is overwrite the tabLength instead of going through the "well, it's the default, write nothing" logic.

**Comment by JellyWX** [comment]
that fix no longer works, sadly (or at least not for me). atom automatically removes lines that are the same as unscoped to save storage

**Comment by JellyWX** [comment]
Sorry this took me so long, i completely forgot about the notification i received from here. Many thanks

**Comment by fserb** [comment]
Glad atom/settings-view folks realized it the issue quickly. :)

**Comment by waalteer** [comment]
Well, manual fix from fserb worked for me using v1.18.0 x64 in ubuntu (soft tabs enabled)
Thanks!

**Comment by gabriel-tessier** [comment]
I use version 1.23.3 on Mac and have the same issue. The fix from fserb work!
Thanks
is it a Zombie bug? We can't kill it!!

**Comment by rippledj** [comment]
I'm going back and forth between Mac OS High Sierra and Ubuntu Linux 16.04.  Whenever I import code from a file created on the other machine which runs fine... I get indentation errors.  Something about Atom is importing the file wrong.  Still in 2018.

**Comment by DarkDataAnalytics** [comment]
I am doing the same thing as rippled and have the same issue.
