### ISSUE TITLE
support for requirements.txt files

### ISSUE THREAD

**Issue by ssbarnea** [atom/language-python#191]
I need support for `requirements.txt` files, so the syntax is recognized.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
