### ISSUE TITLE
cannot adjust visible spaces by window:toggle-invisibles

### ISSUE THREAD

**Issue by alterratz** [atom/language-python#206]
### Description

Why does this module need its own settings for visible spaces. It is very inconvenient to have to go to the module preferences in order to adjust the settings for visible spaces. Just make the language-python use the global settings if no python-specific settings are present.

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
