### ISSUE TITLE
Python code not running

### ISSUE THREAD

**Issue by RafaelZasas** [atom/language-python#270]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Im not able to run print "hello world" after setting the language to python. i get the following error message: "'python' is not recognized as an internal or external command,
operable program or batch file."
please help.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for reaching out!

> Im not able to run print "hello world" after setting the language to python. i get the following error message: "'python' is not recognized as an internal or external command,
> operable program or batch file."
> please help.

This sounds like an issue with a community package you're using rather than an issue with this package.  I'd suggest checking out the [official message board](https://discuss.atom.io) and see if [past posts are helpful](https://discuss.atom.io/search?q=python%27%20is%20not%20recognized%20as%20an%20internal%20or%20external%20command) and if not, asking for help there.

There are a bunch of helpful community members that should be willing to point you in the right direction.
