### ISSUE TITLE
Support richer type annotations

### ISSUE THREAD

**Issue by shadow-light** [atom/language-python#273]
### Description

Richer type annotations are not supported yet.

### Steps to Reproduce

```python
variable:str = 'hi'
def task(arg:special[str]) -> something.something[str, abc.xyz, int]:
    pass
```

**Expected behavior:** All of the given type annotations should be marked
**Actual behavior:** None of them are marked properly

### Versions

50aa96b504a8c8ce24609c2b7ad1c4bc20e6e9d2

### Additional Information

I've created a [very permissive regex](https://github.com/shadow-light/language-python/commit/60a6e16ea4c2c0a44ec0674653686235d9743f25) that works for me, but definitely needs improving before production.

**Comment by nicktimko** [comment]
What does it mean to "mark" the annotations? I'm not that familiar with the the syntax highlighting, but I think one stage of it tags text as being an operator, numeric literal, string, keyword, etc., then the theme highlights based on matching those.

Within the arbitrary expression that the type annotations are, it appears to highlight the elements of the expression akin to any other, `str`, `int` are builtins, `datetime.datetime` isn't so it's just "normal". The `typing` helpers are in the same boat, otherwise "normal" like any non builtin, non keyword.

![image](https://user-images.githubusercontent.com/5297556/54854322-8af11d00-4cc0-11e9-9012-a163495c3b30.png)

```python
import datetime
import typing

class MyDate:
    @classmethod
    def from_datetime(cls, dt: datetime.datetime, do_it: bool = False) -> "MyDate":
        ...

    def __init__(
        self, foo: str, bar: typing.Union[None, typing.Iterable, int] = None
    ) -> None:
        ...
```

What should that look like?

**Comment by shadow-light** [comment]
Oh, by "mark" I meant "tag" with a class.

While types are somewhat just arbitrary code they are also indeed types as well, and it would be helpful to mark them as types as well as whatever thing they are normally. In my case I'd like to put a lower opacity on them so my eyes can naturally ignore them while I focus on actual code.
