### ISSUE TITLE
Update "self" to include a ".self" class

### ISSUE THREAD

**Issue by lee-dohm** [atom/language-python#33]
See: atom/language-coffee-script#39

Per the discussion on the CoffeeScript language package, it makes sense to keep the various default Atom language packages consistent. So rather than `self` being given a class of `variable.language.python` it should be given a class of `variable.language.self.python`.

**Comment by jagill** [comment]
1. Is this something you would want a PR for?
2. If so, would you want 'cls' to be given `variable.language.self.python`, or `variable.language.cls.python`?

**Comment by 50Wliu** [comment]
@jagill Can you clarify what the `cls` keyword is for?  And yes, PRs definitely accepted!

**Comment by jagill** [comment]
`cls` is used instead of `self` for static/class methods, according to [PEP 8](http://legacy.python.org/dev/peps/pep-0008/#function-and-method-arguments).  It is in the same clause in the grammar currently as `self`, so the minimal change is to change the class of both of them, which seems semantically right.

**Comment by 50Wliu** [comment]
OK.  We should probably highlight that with the same .self class then.

**Comment by 50Wliu** [comment]
Fixed by #136.
