### ISSUE TITLE
Respect app-wide preferences

### ISSUE THREAD

**Issue by smenor** [atom/language-python#62]
I set my Atom app preferences to «soft tabs using two spaces» but the editor kept indenting by four. Finally I dug into the language-python settings and found that (a) it's using hard tabs despite my app wide preference to use soft tabs and (b) it's ignoring my two spaces setting and rendering the hard tabs as four spaces - both of which are super annoying if you're a bit anal about those things.

**Comment by lee-dohm** [comment]
Would you mind including your config file so that we can get a full picture of the problem?

**Comment by smenor** [comment]
I’m pretty sure I was just using the out of the box config files. 


The Python tabs below I had to set (also note it’s still using hard tabs there)

"*":
  "exception-reporting":
    userId: "11a9f06f-ae8d-d0bb-025f-383f65b95af7"
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
    softWrap: true
    showInvisibles: true
    showIndentGuide: true
".python.regexp.source":
  editor:
    tabLength: 2
".python.source":
  editor:
    tabLength: 2

**Comment by 50Wliu** [comment]
It's `.source.python`, not the other way around.

**Comment by smenor** [comment]
Sorry I occasionally transpose things

**Comment by lee-dohm** [comment]
@50Wliu the Atom config writer transposes them sometimes, but since it is based on CSS selectors, the order doesn't matter :grinning:

@smenor The global settings are overridden by scope-specific settings. *But*, language packages can define defaults for a language that take precedence over your global settings and then you can override those. This way languages that require one or the other (and there are some), the language package can prevent people from making mistakes.

So, with that in mind, are you saying that we should revert 47ac14ae8b4343c3f2785670a312dd0ec8a71187 even though you can (and obviously have) overridden the language default included in the package?

**Comment by thomasjo** [comment]
> So, with that in mind, are you saying that we should revert 47ac14a

That won't happen. PEP8 clearly states 4 spaces should be used for indentation. I realize you were asking an almost rhetorical question, but I'm gonna :gun: that question right now. This issue has made it obvious that we aren't enforcing soft tabs by default though, and that's clearly a problem. Going to fix that right now. I also disagree with @smenor with regards to "app-wide" setting aspect. The way it works now is that it acts as the default for any language package that does not otherwise specify it's own defaults. Hopefully at some point these types of settings will be more discoverable (see https://github.com/atom/settings-view/issues/284).

**Comment by smenor** [comment]
I didn't know about PEP8 (that's pretty disappointing, actually, though I guess it's necessary since Python is intrinsically broken thanks to semantic whitespace and lacking block delimeters).

It makes no difference to me now because I've adjusted the settings to my preferences, but I have to imagine there will be many other people who want soft tabs of n-spaces, set that as the default, and then are surprised or frustrated to find that Atom is (from their perspective randomly) doing something else.

**Comment by lee-dohm** [comment]
I think there's definitely a solution somewhere amongst all these options, whether better settings visualization or something like my [indentation-indicator package](https://atom.io/packages/indentation-indicator) or something else in addition. I think we do want to keep the settings that nudge users in the "right direction" by default though, even if it is a little more confusing at first. We've just got to figure out how to reduce or resolve that confusion.

**Comment by Alhadis** [comment]
Another issue that would be easily solved with the use of hard tabs.

Just putting that out there. 0=)

FYI, I forcefully override this default of 4-space soft tabs by manually copy+pasting a hard tab from another document, indenting a few lines in Python, and letting the [auto-detect-indentation](https://github.com/jtokoph/auto-detect-indentation) plugin do its work. ^^

**Comment by 50Wliu** [comment]
Closing since PEP8 is the defacto coding standard for Python.
