### ISSUE TITLE
Highlight and, or, not, is keywords

### ISSUE THREAD

**Issue by rumpelsepp** [atom/language-python#98]
Logical keywords, for instance `and`, `or`, `not` and `is` are not highlighted properly:

![screenshot from 2015-09-22 16-03-45](https://cloud.githubusercontent.com/assets/1961699/10020506/93314ee8-6143-11e5-8cdf-3d66f5c226f4.png)

**Comment by fergyfresh** [comment]
After poking around a bit I can submit a pull with Boolean operator syntax highlighting. I verified the same issue on my machine. There is currently no handling of Boolean operators for highlighting.

**Comment by mnquintana** [comment]
@fergyfresh Go for it! :smile:

**Comment by fergyfresh** [comment]
@mrquintana is there something I should do before I submit the pull? Other than obviously verifying it works for me? Or will the travis build pass/fail be the ultimate judgment on whether or not my pull is acceptable?

**Comment by mnquintana** [comment]
You'll need to add specs testing this change to `spec/python-spec.coffee`, but otherwise just submit it! We'll review it and see if it needs any tweaking. (Part of it is the Travis build passing though.)

**Comment by fergyfresh** [comment]
@rumpelsepp is this with python2 or python3?

**Comment by rumpelsepp** [comment]
The screenshot I have posted is with python3

**Comment by fergyfresh** [comment]
@rumpelsepp when did you last update your plug-in? I have just tested this in python2 and python3 on a RedHat 7.1 install and it worked fine. All of the Boolean operators worked fine. I would like to see if anyone else can verify that this is an issue because I disabled every plug-in besides the language-python for the atom install on the RedHat machine and all of the Boolean operators worked for the EXACT string you specified in the screenshot. I would like to know more information about it not working after you have updated atom and all of your plug-ins.

**Comment by mnquintana** [comment]
I can't reproduce this either with 1.2.0-dev-0145ae3 - what version of Atom are you using @rumpelsepp?

**Comment by rumpelsepp** [comment]
I guess it was 1.0.13 or something; but try out the `base16` colorscheme, maybe the problem lies there...

**Comment by fergyfresh** [comment]
@rumpelsepp @mnquintana I tried it with the base16 color (Dark and Light) themes. It appears that the base text color and the Boolean operator color evaluate to the same color in the base16 theme.

**Comment by 50Wliu** [comment]
Ok, in that case can you please file an issue on the base16 themes? [light](https://github.com/atom/base16-tomorrow-light-theme) and [dark](https://github.com/atom/base16-tomorrow-dark-theme)
